apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommender-pvc 
  namespace: sw462
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
  volumeName: project2-pv-sw462
  storageClassName: standard